# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "*/10 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: isther
          template: classic
          base: header, repositories
          config_octicon: yes
          config_presets: @ther
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_pagespeed: yes
          plugin_pagespeed_url: .user.website
          plugin_wakatime: yes
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com/@ther
          plugin_wakatime_user: ther
          repositories_skipped: isther.github.io