name: Update readme
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: main.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg
          oken: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_days: 365
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
            

