# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Readme
on:
  # Schedule updates (each hour)
  schedule: [{cron: "30 18 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
