# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Readme
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 12 1/2 * ?"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Main
        uses: lowlighter/metrics@latest
        with:
          user: isther
          template: classic
          base: header
          filename: main.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Shanghai
      - name: Lines
        uses: lowlighter/metrics@latest
        with:
          filename: lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
