# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Readme
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.wakatime.svg
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_days: 365     
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
          plugin_wakatime_url: http://wakapi.dev                  # Wakatime url endpoint
          plugin_wakatime_user: .user.login             
